### ISSUE TITLE
aria-controls attr

### ISSUE THREAD

**Issue by svinkle** [alexcarpenter/butane-dropdown#4]
Just wondering where the `aria-controls` attribute is being set? This might be a barrier of adoption if this relies on specific HTML. I might suggest adding this attribute dynamically as well as setting the `id` dynamically if possible.

https://github.com/alexcarpenter/butane-dropdown/blob/1257a77f52f28025d38b94dfbccbd1eedf33d782/src/main.js#L21

**Comment by alexcarpenter** [comment]
This is now dynamically added based off of `data-butane-dropdown-controls`.
