### ISSUE TITLE
Buttons as items

### ISSUE THREAD

**Issue by svinkle** [alexcarpenter/butane-dropdown#5]
While I think `button` works well for the menu items, for some reason I feel this selector is too specific. I can imagine someone making an `li` with `role="menuitem"` or maybe even a `div`. Consider adding a class for each menu item and create the `menuItems` node list from this class selector.

https://github.com/alexcarpenter/butane-dropdown/blob/1257a77f52f28025d38b94dfbccbd1eedf33d782/src/main.js#L37

**Comment by alexcarpenter** [comment]
As of https://github.com/alexcarpenter/butane-dropdown/commit/0386e22c1bd5ca11adbe046c7e4d71d5c4762871 this now allows you to use different elements as menuitems.
