### ISSUE TITLE
Loop method

### ISSUE THREAD

**Issue by svinkle** [alexcarpenter/butane-dropdown#6]
Wondering why not use `for…of` here? Something like:
```javascript
for (const item of this.menuItems) {
  item.setAttribute('role', 'menuitem')
}
```

I mean, it's fine as is, just think this is easier to read. Though, I suppose [old browser support](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of#Browser_compatibility) would be a legit reason to _not_ use `for…of`. 🙂

https://github.com/alexcarpenter/butane-dropdown/blob/1257a77f52f28025d38b94dfbccbd1eedf33d782/src/main.js#L43

**Comment by alexcarpenter** [comment]
Yeah, I think I will keep it as is for the the older browser support.
