### ISSUE TITLE
Creating events on show and hide

### ISSUE THREAD

**Issue by svinkle** [alexcarpenter/butane-dropdown#8]
Creating event handlers on `showDropdown()` and `hideDropdown()` I imagine will not be good for perf or memory usage.

I tried these changes out to get around this. A bit of refactoring should do the trick:

```javascript
  // …
  this.buttonElement.addEventListener('click', this._toggleDropdown)
  document.addEventListener('keydown', this._bindKeyPress)
}

toggleDropdown () {
  this.menu.hidden ? this._showDropdown() : this._hideDropdown()
}

showDropdown () {
  this.menu.hidden = false
  this.buttonElement.setAttribute('aria-expanded', true)

  this.menuItemFirst.focus()
}

hideDropdown () {
  this.menu.hidden = true
  this.buttonElement.setAttribute('aria-expanded', false)

  this.buttonElement.focus()
}
```

https://github.com/alexcarpenter/butane-dropdown/blob/1257a77f52f28025d38b94dfbccbd1eedf33d782/src/main.js#L72

**Comment by alexcarpenter** [comment]
@svinkle This does clean it up a bit, but I am confused how this would be better seeings that the keydown event would always be listening vs only listening when needed?

**Comment by svinkle** [comment]
Well, that's sort of the point of an event listener; always be listening. When adding the event listener within your `showDropdown()` and `hideDropdown()` methods, you're re-adding the listener over and over, eating up system memory.

Looking at this again, instead of attaching the event listener to the `document` you could get away with attaching to something more local, like the container `div`. This works well and limits the event to only fire when something inside the container has focus.

```javascript
this.container = document.querySelector('.c-dropdown')
// …
this.container.addEventListener('keydown', this._bindKeyPress)
```

**Comment by alexcarpenter** [comment]
@svinkle good to know, updated in https://github.com/alexcarpenter/butane-dropdown/commit/45c6d43cf9dc0a61784ed682c1ed4deff538d6ad
