### ISSUE TITLE
Create demo page

### ISSUE THREAD

**Issue by svinkle** [alexcarpenter/butane-dropdown#9]
You could easily create a demo page for people to quickly checkout by issuing this command:

```sh
git subtree push --prefix docs origin gh-pages
```

This grabs the files in your `/docs` directory and pushes it to the `gh-pages` branch. GitHub will host the files in this branch at https://alexcarpenter.github.io/butane-dropdown

Then you could update your README file with this link. 🙂

**Comment by svinkle** [comment]
Oh weird, this already exists. I guess you have it setup some other way, lol. 👍

**Comment by alexcarpenter** [comment]
@svinkle yeah I am using the `/docs` folder to house the demo.
